version: '3.9'
services:
  backend:
    build: ./src/OnlineTestSystem.Api/
    ports:
      - '5000:5000'
    environment:
      ConnectionStrings:DefaultConnection: Host=db;Port=5432;Database=testsdb;Username=postgres;Password=secret;
    restart: always
  frontend:
    build: ./src/OnlineTestSystem.Client/
    ports:
      - '3000:80'
    depends_on:
      - 'backend'
    restart: always
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
     - 5432:5432 